"""M2 Functionalization tab — extracted from app.py for UI restructure.

v6.0: Renders the complete M2 Surface Functionalization tab including inputs,
run button, and results display. All widget keys preserved exactly (m2_* prefix).
Widget key pattern includes step_type AND reagent_key (Codex R3-F4 fix).

v0.3.0 (B3): reagent dropdowns are filtered by the recipe's polymer_family —
``incompatible`` entries (per the family × reagent matrix) are dropped, and
``qualitative_only`` entries get a "⚠ qualitative-only" suffix. M2 result
panels render evidence-tier badges next to the per-step expanders.
"""

from __future__ import annotations

import streamlit as st

from dpsim.datatypes import ModelEvidenceTier, PolymerFamily
from dpsim.lifecycle import resolve_lifecycle_inputs
from dpsim.module2_functionalization.family_reagent_matrix import (
    check_family_reagent_compatibility,
)
from dpsim.properties.database import PropertyDatabase
from dpsim.trust import assess_trust
from dpsim.visualization.ui_recipe import (
    ensure_process_recipe_state,
    save_process_recipe_state,
    sync_m2_steps_to_recipe,
)


_M2_TIER_COLORS = {
    ModelEvidenceTier.VALIDATED_QUANTITATIVE: ":green[VALIDATED]",
    ModelEvidenceTier.CALIBRATED_LOCAL: ":green[CALIBRATED]",
    ModelEvidenceTier.SEMI_QUANTITATIVE: ":orange[SEMI-QUANTITATIVE]",
    ModelEvidenceTier.QUALITATIVE_TREND: ":red[QUALITATIVE TREND]",
    ModelEvidenceTier.UNSUPPORTED: ":red[UNSUPPORTED]",
}


def _m2_evidence_tier_badge(result_obj) -> str:
    """Return a tier badge string for an M2 step result; empty if no manifest."""
    manifest = getattr(result_obj, "model_manifest", None)
    if manifest is None:
        return ""
    tier = getattr(manifest, "evidence_tier", None)
    if tier is None:
        return ""
    badge = _M2_TIER_COLORS.get(tier, str(getattr(tier, "value", tier)))
    return f"Evidence: {badge} | Model: `{getattr(manifest, 'model_name', '')}`"


def _active_polymer_family() -> PolymerFamily:
    """Resolve the active polymer family from the session-state recipe.

    The recipe may be either a dataclass-like object (legacy
    LifecycleRecipe) or a plain dict (newer JSON-deserialised form);
    both shapes appear in the wild depending on how the recipe was
    constructed. Defensively read both.
    """
    recipe = st.session_state.get("process_recipe")
    if recipe is None:
        return PolymerFamily.AGAROSE_CHITOSAN

    # Resolve material_batch from either object-attribute or dict access.
    mb = getattr(recipe, "material_batch", None)
    if mb is None and isinstance(recipe, dict):
        mb = recipe.get("material_batch")
    if mb is None:
        return PolymerFamily.AGAROSE_CHITOSAN

    # Resolve polymer_family from material_batch (same dual-shape rule).
    polymer_family_value = getattr(mb, "polymer_family", None)
    if polymer_family_value is None and isinstance(mb, dict):
        polymer_family_value = mb.get("polymer_family")
    if not polymer_family_value:
        return PolymerFamily.AGAROSE_CHITOSAN

    raw = str(polymer_family_value).strip().lower()
    try:
        return PolymerFamily(raw)
    except ValueError:
        return PolymerFamily.AGAROSE_CHITOSAN


# ── M2 Chemistry buckets (v0.3.4 — UI audit fix) ─────────────────────────
# Each user-facing "Chemistry" radio choice maps to a tuple of
# functional_mode values from REAGENT_PROFILES. The reagent-options dict
# for each bucket is generated by _reagent_options_for_bucket() instead of
# being hardcoded, so every reagent shipped in REAGENT_PROFILES auto-
# surfaces in the dropdown. This closes the UI audit gap that left 44 of
# 94 backend reagents invisible to users (the v9.2 / v9.3 / v9.4 chemistry
# classes never reached the dropdown because the old if/elif chain only
# listed the v9.1 baseline).
#
# Coverage discipline: every value in ALLOWED_FUNCTIONAL_MODES MUST appear
# in exactly one bucket here. Enforced by
# tests/test_v0_3_4_m2_dropdown_coverage.py.
_BUCKET_TO_MODES: dict[str, tuple[str, ...]] = {
    # v9.1 baseline buckets — preserved verbatim for session-state
    # continuity; their contents grow to absorb the v9.2-v9.4 additions.
    "Secondary Crosslinking": ("crosslinker",),
    "Hydroxyl Activation": ("activator",),
    "Ligand Coupling": (
        "iex_ligand", "hic_ligand", "imac_chelator",
        "gst_affinity", "heparin_affinity",
    ),
    "Protein Coupling": ("affinity_ligand", "biotin_affinity"),
    "Spacer Arm": ("spacer", "heterobifunctional_crosslinker"),
    "Metal Charging": ("metal_charging",),
    "Protein Pretreatment": ("protein_pretreatment",),
    "Washing": ("washing",),
    "Quenching": ("quencher",),
    # v0.3.4 new buckets — surface the v9.2-v9.4 chemistry classes that
    # had no place to render under the old taxonomy.
    "Click Chemistry": ("click_handle",),
    "Dye Pseudo-Affinity": ("dye_pseudo_affinity",),
    "Mixed-Mode HCIC": ("mixed_mode_hcic",),
    "Thiophilic": ("thiophilic",),
    "Boronate": ("boronate",),
    "Peptide Affinity": ("peptide_affinity",),
    "Oligonucleotide": ("oligonucleotide",),
    "Material-as-Ligand": ("material_as_ligand",),
}

# Bucket render order in the Chemistry radio. Preserves the v9.1 layout at
# the top (so existing user habits aren't disrupted) and groups the new
# v0.3.4 buckets at the bottom.
_BUCKET_DISPLAY_ORDER: tuple[str, ...] = (
    "Secondary Crosslinking",
    "Hydroxyl Activation",
    "Ligand Coupling",
    "Protein Coupling",
    "Spacer Arm",
    "Metal Charging",
    "Protein Pretreatment",
    "Washing",
    "Quenching",
    # v0.3.4 additions
    "Click Chemistry",
    "Dye Pseudo-Affinity",
    "Mixed-Mode HCIC",
    "Thiophilic",
    "Boronate",
    "Peptide Affinity",
    "Oligonucleotide",
    "Material-as-Ligand",
)


def _reagent_options_for_bucket(bucket: str) -> dict[str, str]:
    """Return ``{display_label: reagent_key}`` for a Chemistry bucket.

    Driven by ``REAGENT_PROFILES.functional_mode``; uses each profile's
    ``.name`` field as the display label. Sort order is alphabetical by
    label for predictability. Unknown bucket → empty dict (caller
    surfaces a "no reagents in this bucket" advisory).
    """
    from dpsim.module2_functionalization.reagent_profiles import (
        REAGENT_PROFILES as _RP,
    )

    modes = _BUCKET_TO_MODES.get(bucket, ())
    if not modes:
        return {}
    pairs: list[tuple[str, str]] = []
    for key, profile in _RP.items():
        mode = getattr(profile, "functional_mode", "")
        if mode in modes:
            label = getattr(profile, "name", "") or key.replace("_", " ").title()
            pairs.append((label, key))
    pairs.sort(key=lambda pair: pair[0].lower())
    return {label: key for label, key in pairs}


def _family_filter_reagents(
    options: dict[str, str],
    family: PolymerFamily,
) -> dict[str, str]:
    """Filter / annotate a reagent-options dict against the family-reagent matrix.

    Compatibility values:
      - compatible           → keep label unchanged
      - qualitative_only     → suffix label with "⚠ qualitative-only"
      - incompatible         → drop entry
      - None (no opinion)    → keep label unchanged
    """
    filtered: dict[str, str] = {}
    for label, key in options.items():
        entry = check_family_reagent_compatibility(family, key)
        if entry is None or entry.compatibility == "compatible":
            filtered[label] = key
        elif entry.compatibility == "qualitative_only":
            filtered[f"{label} ⚠ qualitative-only"] = key
        # incompatible → drop
    if not filtered:
        # Don't lock the user out entirely; surface the original options with
        # an advisory caption so they can still make a choice (the G4
        # guardrail will block on run if the choice is incompatible).
        return options
    return filtered


def render_tab_m2(tab_container, _smgr) -> None:
    """Render the M2 Functionalization tab inside the given Streamlit container.

    Args:
        tab_container: Streamlit tab container from st.tabs().
        _smgr: SessionStateManager instance.
    """
    with tab_container:
        # v0.4.14: Direction-A page-header pair replacing legacy st.header.
        from dpsim.visualization.design import chrome as _chrome
        st.html(_chrome.eyebrow("Stage 03 · M2", accent=True))
        st.html('<h1 style="margin:0 0 12px 0;">Functionalisation</h1>')

        # ── Upstream M1 Status Banner ────────────────────────────────────
        if "result" not in st.session_state:
            st.warning("\u26a0\ufe0f Module 1 has not been run yet. Run M1 first to provide upstream data.")
        else:
            _m1r = st.session_state["result"]
            _m1e = _m1r.emulsification
            _m1g = _m1r.gelation
            _m1m = _m1r.mechanical
            st.success(
                f"\u2705 M1 data available \u2014 d32={_m1e.d32*1e6:.2f} um | "
                f"porosity={_m1g.porosity:.1%} | G_DN={_m1m.G_DN/1000:.1f} kPa"
            )

        # ── M2 Inputs (Reagent buckets card) ─────────────────────────────
        from dpsim.module2_functionalization.reagent_profiles import REAGENT_PROFILES as _REAGENT_PROFILES
        from dpsim.module2_functionalization import ModificationStep, ModificationStepType, ACSSiteType

        m2_steps = []
        # v0.4.3: modification-step header migrated to labeled_widget.
        from dpsim.visualization.help import labeled_widget as _lw_m2

        # v0.4.17 (P9): Reagent-bucket overview grid — matches the
        # canonical Direction-A reference's 9-bucket grid (extended to
        # 17 here for full v0.3.4 taxonomy coverage). Buckets currently
        # used by the configured steps are highlighted with the accent
        # ring; clicking is informational-only — actual reagent
        # selection happens in the per-step expanders below.
        with st.container(border=True):
            _bucket_counts = {
                _b: len(_reagent_options_for_bucket(_b))
                for _b in _BUCKET_DISPLAY_ORDER
            }
            _reagent_total = sum(_bucket_counts.values())
            st.html(
                _chrome.card_header_strip(
                    eyebrow_text=(
                        f"Reagent buckets · {_reagent_total} reagents · "
                        f"{len(_BUCKET_DISPLAY_ORDER)} chemistry buckets"
                    ),
                    title="Modification protocol",
                )
            )
            _active_buckets = {
                str(st.session_state.get(f"m2_type_{i}", ""))
                for i in range(int(st.session_state.get("m2_n_steps", 1)))
            }
            _bucket_cells = []
            for _b in _BUCKET_DISPLAY_ORDER:
                _count = _bucket_counts[_b]
                _is_active = _b in _active_buckets
                _bucket_cells.append(
                    '<div style="padding:10px 12px;'
                    + (
                        "background:var(--dps-accent-soft);"
                        "border-left:2px solid var(--dps-accent);"
                        if _is_active
                        else "background:var(--dps-surface);"
                        "border-left:2px solid transparent;"
                    )
                    + "border-top:1px solid var(--dps-border);"
                    "display:flex;justify-content:space-between;"
                    'align-items:center;gap:6px;">'
                    '<span style="font-size:12px;font-weight:500;'
                    + (
                        "color:var(--dps-text);"
                        if _is_active
                        else "color:var(--dps-text-muted);"
                    )
                    + f'">{_b}</span>'
                    '<span class="dps-mono" style="font-size:11px;'
                    f'color:var(--dps-text-dim);">{_count}</span>'
                    "</div>"
                )
            st.html(
                '<div style="display:grid;'
                "grid-template-columns:repeat(auto-fill,minmax(180px,1fr));"
                "gap:0;border:1px solid var(--dps-border);"
                'border-radius:3px;overflow:hidden;margin-top:6px;">'
                + "".join(_bucket_cells)
                + "</div>"
            )
        n_m2_steps = _lw_m2(
            "Modification steps",
            help=(
                "Number of M2 chemistry steps to apply in order. "
                "Each step is one expander below; 0–3 supported."
            ),
            widget=lambda: st.number_input(
                "Modification Steps", 0, 3, 1, key="m2_n_steps",
                label_visibility="collapsed",
            ),
        )
        for i in range(int(n_m2_steps)):
            with st.expander(f"Step {i + 1}", expanded=(i == 0)):
                step_type = _lw_m2(
                    "Chemistry bucket",
                    help=(
                        "Top 9 buckets are the v9.1 baseline categories; "
                        "the 8 below them surface v9.2/v9.3/v9.4 chemistry "
                        "classes (click, dye, mixed-mode, etc.) that were "
                        "previously dead UI."
                    ),
                    widget=lambda: st.selectbox(
                        "Chemistry",
                        list(_BUCKET_DISPLAY_ORDER),
                        key=f"m2_type_{i}",
                        label_visibility="collapsed",
                    ),
                )
                # v0.3.4: dropdown contents driven by REAGENT_PROFILES via
                # the bucket→functional_mode map. Old hardcoded if/elif
                # chain replaced (M2 dropdown audit fix).
                _reagent_options = _reagent_options_for_bucket(step_type)
                if not _reagent_options:
                    st.warning(
                        f"No reagents registered for the {step_type!r} "
                        f"bucket. Check REAGENT_PROFILES.functional_mode."
                    )
                    continue
                # v0.3.0 (B3): filter reagent options by active polymer family
                # using the family × reagent matrix. Incompatible entries are
                # dropped; qualitative_only entries get a label suffix.
                _active_family = _active_polymer_family()
                _reagent_options_filtered = _family_filter_reagents(
                    _reagent_options, _active_family
                )
                # Key includes step_type to reset selection when chemistry changes
                _reagent_sel_key = f"m2_reagent_{i}_{step_type.replace(' ', '_').lower()}"
                _reagent_label = _lw_m2(
                    "Reagent",
                    help=(
                        "Specific reagent within the selected bucket. "
                        "Filtered by polymer-family compatibility; "
                        "incompatible reagents are hidden."
                    ),
                    widget=lambda: st.selectbox(
                        "Reagent",
                        list(_reagent_options_filtered.keys()),
                        key=_reagent_sel_key,
                        label_visibility="collapsed",
                    ),
                )
                # Defensive: if Streamlit returns a stale label from session state, fall back to first option
                _reagent_key = _reagent_options_filtered.get(
                    _reagent_label, list(_reagent_options_filtered.values())[0]
                )
                if _active_family != PolymerFamily.AGAROSE_CHITOSAN:
                    st.caption(
                        f"Reagent options filtered for polymer_family="
                        f"`{_active_family.value}`."
                    )

                _profile = _REAGENT_PROFILES.get(_reagent_key)
                if _profile is None:
                    _reagent_key = list(_reagent_options.values())[0]
                    _profile = _REAGENT_PROFILES[_reagent_key]
                st.caption(f"k={_profile.k_forward:.1e} | E_a={_profile.E_a / 1000:.0f} kJ/mol")
                # v0.3.5 (UI audit fix 4): surface ACSSiteType for the
                # selected reagent so users see which surface group is
                # consumed (target_acs) and which is installed
                # (product_acs). Closes the "16 of 25 ACSSiteType
                # entries unsurfaced" gap from the v0.3.3 audit.
                _target_acs = getattr(_profile, "target_acs", None)
                _product_acs = getattr(_profile, "product_acs", None)
                if _target_acs is not None:
                    _t_label = getattr(_target_acs, "value", str(_target_acs))
                    if _product_acs is not None:
                        _p_label = getattr(_product_acs, "value", str(_product_acs))
                        st.caption(
                            f"Surface chemistry: `{_t_label}` → `{_p_label}`"
                        )
                    else:
                        st.caption(f"Targets surface group: `{_t_label}`")
                # Audit F16: display confidence, calibration, hazard
                _conf = getattr(_profile, 'confidence_tier', 'semi_quantitative')
                _cal = getattr(_profile, 'calibration_source', '')[:60]
                _haz = getattr(_profile, 'hazard_class', '') or 'low'
                st.caption(f"Confidence: {_conf} | Hazard: {_haz}")
                st.markdown(
                    f"[View mechanism & protocol](/reagent_detail"
                    f"?key={_reagent_key}&source=reagent_profiles"
                    f"&T={_profile.temperature_default}&t={_profile.time_default}"
                    f"&c=10.0&pH={_profile.ph_optimum})",
                )

                # Spacer selectbox for coupling/protein steps
                if step_type in ("Ligand Coupling", "Protein Coupling"):
                    _spacer_options = {
                        "None (Direct Coupling)": "",
                        "DADPA (13 A, EAH-standard)": "dadpa_spacer",
                        "AHA (10 A, NHS-standard)": "aha_spacer",
                        "DAH (9 A, AH-standard)": "dah_spacer",
                    }
                    # v0.4.5: spacer arm migrated to labeled_widget.
                    _spacer_label = _lw_m2(
                        "Spacer arm",
                        help=(
                            "Spacer arm between the bead surface and the "
                            "ligand. Reduces steric hindrance for large "
                            "analytes. Length-class encoded in the option "
                            "label (e.g. 'C6 hexyl' = 6 atoms)."
                        ),
                        widget=lambda: st.selectbox(
                            "Spacer Arm (optional)",
                            list(_spacer_options.keys()),
                            key=f"m2_spacer_{i}_{step_type.replace(' ', '_').lower()}",
                            label_visibility="collapsed",
                        ),
                    )
                    _selected_spacer = _spacer_options.get(_spacer_label, "")

                # Keys include step_type AND reagent so switching either resets defaults (Codex R3-F4)
                _wk = f"{step_type.replace(' ', '_').lower()}_{_reagent_key}"
                # v0.4.2: migrated to labeled_widget for inline help on every
                # reagent-step parameter. Help text is per-parameter rather
                # than per-reagent — the per-reagent context is already in
                # the linked mechanism page below.
                from dpsim.visualization.help import labeled_widget
                _conc = labeled_widget(
                    "Concentration",
                    help=(
                        "Reagent concentration in mM. Drives both reaction "
                        "rate and side-product load. Stay within the "
                        "reagent's calibrated range (see protocol link)."
                    ),
                    unit="mM",
                    widget=lambda: st.number_input(
                        "Concentration (mM)", 0.5, 200.0, 10.0,
                        key=f"m2_conc_{i}_{_wk}", label_visibility="collapsed",
                    ),
                )
                _temp_C = labeled_widget(
                    "Temperature",
                    help=(
                        "Reaction temperature in °C. Default is the "
                        "reagent profile's calibrated temperature; "
                        "deviations affect both rate and selectivity."
                    ),
                    unit="°C",
                    widget=lambda: st.slider(
                        "Temperature (C)", 4, 80,
                        int(_profile.temperature_default - 273.15),
                        key=f"m2_temp_{i}_{_wk}", label_visibility="collapsed",
                    ),
                )
                # v0.3.7 (UI run-fix): minimum lowered from 0.25 h to 0.05 h
                # to accommodate v9.x reagents with shorter time_default
                # (cnbr / hrp / tresyl / alcl3 at 600 s = 0.167 h; borax at
                # 300 s = 0.083 h).
                _time_h = labeled_widget(
                    "Reaction time",
                    help=(
                        "Hold time in hours. Below the reagent's calibrated "
                        "minimum the conversion is incomplete; well above "
                        "it side-reactions accumulate."
                    ),
                    unit="h",
                    widget=lambda: st.number_input(
                        "Time (h)", 0.05, 48.0,
                        float(_profile.time_default / 3600),
                        key=f"m2_time_{i}_{_wk}", label_visibility="collapsed",
                    ),
                )
                _ph = labeled_widget(
                    "pH",
                    help=(
                        "Reaction pH. For coupling chemistries this must "
                        "keep both the activated bead group AND the ligand "
                        "in their reactive ionisation state."
                    ),
                    widget=lambda: st.slider(
                        "pH", 3.0, 14.0, float(_profile.ph_optimum),
                        step=0.5, key=f"m2_ph_{i}_{_wk}",
                        label_visibility="collapsed",
                    ),
                )
                st.markdown(
                    f"[View mechanism & protocol (with your parameters)](/reagent_detail"
                    f"?key={_reagent_key}&source=reagent_profiles"
                    f"&T={_temp_C + 273.15}&t={_time_h * 3600}"
                    f"&c={_conc}&pH={_ph})",
                )

                if step_type == "Protein Coupling":
                    st.caption("Ranking only \u2014 activity retention and steric limits are illustrative defaults.")

                _step_type_map = {
                    # Secondary Crosslinking: target_acs left to the reagent profile so
                    # hydroxyl-targeted crosslinkers (stmp_secondary) work alongside
                    # the amine-targeted default (genipin_secondary, glutaraldehyde_secondary).
                    "Secondary Crosslinking": (ModificationStepType.SECONDARY_CROSSLINKING, None),
                    "Hydroxyl Activation": (ModificationStepType.ACTIVATION, ACSSiteType.HYDROXYL),
                    "Ligand Coupling": (ModificationStepType.LIGAND_COUPLING, None),
                    "Protein Coupling": (ModificationStepType.PROTEIN_COUPLING, None),
                    "Spacer Arm": (ModificationStepType.SPACER_ARM, None),
                    "Metal Charging": (ModificationStepType.METAL_CHARGING, None),
                    "Protein Pretreatment": (ModificationStepType.PROTEIN_PRETREATMENT, None),
                    "Washing": (ModificationStepType.WASHING, None),
                    "Quenching": (ModificationStepType.QUENCHING, None),
                }
                _step_type_enum, _default_target = _step_type_map[step_type]
                if _default_target is not None:
                    _target_acs = _default_target
                else:
                    _target_acs = _REAGENT_PROFILES[_reagent_key].target_acs
                # Set product_acs for activation steps (needed to create EPOXIDE/VS profiles)
                _product_acs = _REAGENT_PROFILES[_reagent_key].product_acs
                m2_steps.append(ModificationStep(
                    step_type=_step_type_enum,
                    reagent_key=_reagent_key,
                    target_acs=_target_acs,
                    product_acs=_product_acs,
                    temperature=_temp_C + 273.15,
                    time=_time_h * 3600,
                    ph=_ph,
                    reagent_concentration=_conc,
                ))

        _recipe = ensure_process_recipe_state(st.session_state)
        _recipe = sync_m2_steps_to_recipe(_recipe, m2_steps)
        save_process_recipe_state(st.session_state, _recipe)

        # ── ACS state — pre-Run preview / live result (v0.4.17 P8) ──────
        # Always-visible card matching the canonical Direction-A
        # reference's "ACS state — predicted" card. Pre-Run renders
        # placeholder cells; post-Run pulls live values from m2_result.
        _m2_post = st.session_state.get("m2_result")
        with st.container(border=True):
            if _m2_post is not None:
                _acs_eyebrow = (
                    f"ACS state · live · "
                    f"{len(_m2_post.acs_profiles)} site-types tracked"
                )
                _acs_evidence = _chrome.evidence_badge(
                    "semi_quantitative", compact=True,
                )
            else:
                _acs_eyebrow = "ACS state · pre-run preview"
                _acs_evidence = _chrome.evidence_badge(
                    "unsupported", compact=True,
                )
            st.html(
                _chrome.card_header_strip(
                    eyebrow_text=_acs_eyebrow,
                    title="25 site-types tracked",
                    right_html=_acs_evidence,
                )
            )
            if _m2_post is not None:
                _g_dn_kpa = _m2_post.G_DN_updated / 1000.0
                _e_star_kpa = _m2_post.E_star_updated / 1000.0
                _n_steps_run = len(_m2_post.modification_history)
                _acs_cells = [
                    ("steps", str(_n_steps_run), "executed",
                     "calibrated_local"),
                    ("G_DN", f"{_g_dn_kpa:.1f}", "kPa",
                     "semi_quantitative"),
                    ("E*", f"{_e_star_kpa:.1f}", "kPa",
                     "semi_quantitative"),
                    ("ligands", f"{len(_m2_post.acs_profiles)}", "types",
                     "qualitative_trend"),
                ]
            else:
                _acs_cells = [
                    ("steps", "—", "configured", "unsupported"),
                    ("G_DN", "—", "kPa", "unsupported"),
                    ("E*", "—", "kPa", "unsupported"),
                    ("ligands", "—", "types", "unsupported"),
                ]
            _acs_grid_cells = []
            for _label, _val, _unit, _tier in _acs_cells:
                _acs_grid_cells.append(
                    '<div style="padding:8px 10px;'
                    "background:var(--dps-surface-2);"
                    "border:1px solid var(--dps-border);"
                    'border-radius:4px;display:flex;flex-direction:column;'
                    'gap:4px;">'
                    '<div style="display:flex;align-items:center;'
                    'justify-content:space-between;gap:6px;">'
                    + _chrome.eyebrow(_label)
                    + _chrome.evidence_badge(_tier, compact=True)
                    + "</div>"
                    + _chrome.metric_value(value=_val, unit=_unit, size=16)
                    + "</div>"
                )
            st.html(
                '<div style="display:grid;'
                'grid-template-columns:repeat(4,1fr);gap:8px;'
                'margin-top:4px;">'
                + "".join(_acs_grid_cells)
                + "</div>"
            )
            if _m2_post is None:
                st.caption(
                    "Run M2 to populate the ACS profile · 25 site-types "
                    "tracked across the 17 chemistry buckets."
                )

        # ── Run M2 Button ────────────────────────────────────────────────
        st.divider()
        _m2_can_run = "result" in st.session_state and len(m2_steps) > 0
        # v0.4.17 (P4): pre-Run status strip \u2014 shows step count, blocker
        # state, and family-filter context before the user clicks Run.
        # Colour follows the canonical Direction-A semantic palette:
        # green = ready, amber = warnings only, red = recipe blockers.
        _m2_n_steps = len(m2_steps)
        if "result" not in st.session_state:
            _m2_status_color = "var(--dps-amber-500)"
            _m2_status_text = "M1 not yet run \u00b7 run M1 first"
        elif _m2_n_steps == 0:
            _m2_status_color = "var(--dps-amber-500)"
            _m2_status_text = "no modification steps configured"
        else:
            _m2_status_color = "var(--dps-green-500)"
            _m2_status_text = (
                f"{_m2_n_steps} step{'s' if _m2_n_steps != 1 else ''} configured \u00b7 "
                "ready to run"
            )
        st.html(
            '<div style="display:flex;align-items:center;gap:10px;'
            "padding:8px 12px;margin-bottom:8px;"
            "background:var(--dps-surface-2);"
            f'border:1px solid {_m2_status_color};border-radius:4px;">'
            f'<span style="width:8px;height:8px;border-radius:50%;'
            f'background:{_m2_status_color};display:inline-block;"></span>'
            '<span class="dps-mono" style="font-size:11.5px;'
            f'color:{_m2_status_color};font-weight:600;'
            'letter-spacing:0.04em;text-transform:uppercase;">M2</span>'
            f'<span style="font-size:12.5px;color:var(--dps-text);">'
            f"{_m2_status_text}</span>"
            "</div>"
        )
        m2_run_btn = st.button("\u25b6 Run M2: Functionalization", type="primary",
                                use_container_width=True, disabled=not _m2_can_run)

        if m2_run_btn:
            _smgr.invalidate_downstream(from_module=2)
            with st.spinner("Running Module 2: Functionalization..."):
                from dpsim.pipeline.orchestrator import export_for_module2
                from dpsim.module2_functionalization import ModificationOrchestrator

                _m1_result = st.session_state["result"]
                _m1_params = st.session_state["params"]
                _m1_overrides = st.session_state.get("m1_overrides", {})
                _m1_xl_key = st.session_state.get("m1_xl_key", "genipin")
                _m1_l2_mode = st.session_state.get("m1_l2_mode", "empirical")
                _recipe = ensure_process_recipe_state(st.session_state)
                _recipe = sync_m2_steps_to_recipe(_recipe, m2_steps)
                _resolved = resolve_lifecycle_inputs(_recipe, base_params=_m1_params)
                _m2_blockers = [issue for issue in _resolved.validation.blockers if issue.module == "M2"]
                if _m2_blockers:
                    for _issue in _m2_blockers:
                        st.error(f"M2 recipe blocker: {_issue.message}")
                    st.stop()
                _m2_steps_for_run = _resolved.functionalization_steps
                _m1_params = _resolved.parameters
                st.session_state["params"] = _m1_params
                save_process_recipe_state(st.session_state, _recipe)

                db_trust = PropertyDatabase()
                props_trust_m2 = db_trust.update_for_conditions(
                    _m1_params.formulation.T_oil, _m1_params.formulation.c_agarose,
                    _m1_params.formulation.c_chitosan, _m1_params.formulation.c_span80,
                )
                for _k, _v in _m1_overrides.items():
                    if hasattr(props_trust_m2, _k):
                        setattr(props_trust_m2, _k, _v)
                _trust_m2 = assess_trust(_m1_result, _m1_params, props_trust_m2,
                                         crosslinker_key=_m1_xl_key, l2_mode=_m1_l2_mode)
                try:
                    _contract = export_for_module2(
                        _m1_result, _trust_m2,
                        crosslinker_key=_m1_xl_key,
                        props=props_trust_m2,
                    )
                    _m2_orch = ModificationOrchestrator()
                    _m2_result = _m2_orch.run(_contract, _m2_steps_for_run)
                    st.session_state["m2_result"] = _m2_result
                    st.session_state["m1_contract"] = _contract
                except Exception as _m2_ex:
                    st.error(f"Module 2 failed: {_m2_ex}")
                    st.session_state.pop("m2_result", None)
                    st.stop()  # Don't rerun — show the error
            st.rerun()

        # ── M2 Results Display ───────────────────────────────────────────
        if "m2_result" in st.session_state:
            from dpsim.visualization.plots_m2 import plot_acs_waterfall, plot_surface_area_comparison
            _m2 = st.session_state["m2_result"]

            st.divider()

            # ── ACS state card ───────────────────────────────────────────
            with st.container(border=True):
                st.html(
                    _chrome.card_header_strip(
                        eyebrow_text=(
                            f"ACS state — predicted / "
                            f"{len(_m2.acs_profiles)} site-types tracked"
                        ),
                        title="M2 Results",
                    )
                )
                _mc1, _mc2, _mc3 = st.columns(3)
                _mc1.metric("Steps Executed", len(_m2.modification_history))
                _mc2.metric("G_DN Updated", f"{_m2.G_DN_updated / 1000:.1f} kPa")
                _mc3.metric("E* Updated", f"{_m2.E_star_updated / 1000:.1f} kPa")

                st.divider()

                st.markdown("**ACS Site Inventory (remaining after all steps)**")
                for _site_type, _profile in _m2.acs_profiles.items():
                    st.write(f"**{_site_type.value}**: remaining = {_profile.remaining_sites:.2e} mol/particle")

                st.divider()

                st.markdown("**Modification History**")
                for _i, _mr in enumerate(_m2.modification_history):
                    _tgt = _mr.step.target_acs
                    _sites_before = _mr.acs_before.get(_tgt)
                    _consumed_str = ""
                    if _sites_before is not None:
                        _consumed = _mr.conversion * _sites_before.remaining_sites
                        _consumed_str = f" | sites consumed: {_consumed:.2e} mol/particle"
                    st.write(
                        f"Step {_i + 1}: {_mr.step.reagent_key} — "
                        f"conversion {_mr.conversion:.1%}{_consumed_str}"
                    )
                    # v0.3.0 (B3): per-step evidence-tier badge.
                    _step_badge = _m2_evidence_tier_badge(_mr)
                    if _step_badge:
                        st.caption(_step_badge)

                st.divider()

                _fig_wf = plot_acs_waterfall(_m2.modification_history)
                if _fig_wf is not None:
                    st.plotly_chart(_fig_wf, use_container_width=True)
                _fig_sa = plot_surface_area_comparison(_m2.surface_model)
                if _fig_sa is not None:
                    st.plotly_chart(_fig_sa, use_container_width=True)

            # ── Wet-lab caveats card ─────────────────────────────────────
            with st.container(border=True):
                st.html(
                    _chrome.card_header_strip(
                        eyebrow_text="Wet-lab caveats / Validation report",
                        title="Model limitations",
                    )
                )
                st.caption(
                    "[!] semi_quantitative — ACS inventory uses simplified site-density model. "
                    "Default rate constants are illustrative — user calibration required."
                )

